### ISSUE TITLE
Trino fail to start in demo 

### ISSUE THREAD

**Issue by yegangy0718** [apache/incubator-xtable#390]
trino           | 2024-03-19T19:53:44.178Z	ERROR	main	io.trino.server.Server	No service providers of type io.trino.spi.Plugin in the classpath: [file:/data/trino/plugin/thrift/HdrHistogram-2.1.9.jar, file:/data/trino/plugin/thrift/aopalliance-1.0.jar, file:/data/trino/plugin/thrift/asm-9.6.jar, file:/data/trino/plugin/thrift/asm-analysis-9.6.jar, file:/data/trino/plugin/thrift/asm-tree-9.6.jar, file:/data/trino/plugin/thrift/asm-util-9.6.jar, file:/data/trino/plugin/thrift/bootstrap-235.jar, file:/data/trino/plugin/thrift/byte-buddy-1.14.8.jar, file:/data/trino/plugin/thrift/bytecode-1.5.jar, file:/data/trino/plugin/thrift/checker-qual-3.37.0.jar, file:/data/trino/plugin/thrift/classmate-1.5.1.jar, file:/data/trino/plugin/thrift/concurrent-235.jar, file:/data/trino/plugin/thrift/configuration-235.jar, file:/data/trino/plugin/thrift/drift-api-1.21.jar, file:/data/trino/plugin/thrift/drift-client-1.21.jar, file:/data/trino/plugin/thrift/drift-codec-1.21.jar, file:/data/trino/plugin/thrift/drift-protocol-1.21.jar, file:/data/trino/plugin/thrift/drift-transport-netty-1.21.jar, file:/data/trino/plugin/thrift/drift-transport-spi-1.21.jar, file:/data/trino/plugin/thrift/error_prone_annotations-2.22.0.jar, file:/data/trino/plugin/thrift/failureaccess-1.0.1.jar, file:/data/trino/plugin/thrift/guava-32.1.2-jre.jar, file:/data/trino/plugin/thrift/guice-7.0.0.jar, file:/data/trino/plugin/thrift/hibernate-validator-8.0.1.Final.jar, file:/data/trino/plugin/thrift/http-client-235.jar, file:/data/trino/plugin/thrift/http2-client-11.0.15.jar, file:/data/trino/plugin/thrift/http2-common-11.0.15.jar, file:/data/trino/plugin/thrift/http2-hpack-11.0.15.jar, file:/data/trino/plugin/thrift/http2-http-client-transport-11.0.15.jar, file:/data/trino/plugin/thrift/j2objc-annotations-2.8.jar, file:/data/trino/plugin/thrift/jackson-core-2.15.2.jar, file:/data/trino/plugin/thrift/jackson-databind-2.15.2.jar, file:/data/trino/plugin/thrift/jackson-datatype-guava-2.15.2.jar, file:/data/trino/plugin/thrift/jackson-datatype-jdk8-2.15.2.jar, file:/data/trino/plugin/thrift/jackson-datatype-joda-2.15.2.jar, file:/data/trino/plugin/thrift/jackson-datatype-jsr310-2.15.2.jar, file:/data/trino/plugin/thrift/jackson-module-parameter-names-2.15.2.jar, file:/data/trino/plugin/thrift/jakarta.annotation-api-2.1.1.jar, file:/data/trino/plugin/thrift/jakarta.inject-api-2.0.1.jar, file:/data/trino/plugin/thrift/jakarta.validation-api-3.0.2.jar, file:/data/trino/plugin/thrift/jboss-logging-3.4.3.Final.jar, file:/data/trino/plugin/thrift/jcl-over-slf4j-2.0.9.jar, file:/data/trino/plugin/thrift/jetty-alpn-client-11.0.15.jar, file:/data/trino/plugin/thrift/jetty-alpn-java-client-11.0.15.jar, file:/data/trino/plugin/thrift/jetty-client-11.0.15.jar, file:/data/trino/plugin/thrift/jetty-http-11.0.15.jar, file:/data/trino/plugin/thrift/jetty-io-11.0.15.jar, file:/data/trino/plugin/thrift/jetty-util-11.0.15.jar, file:/data/trino/plugin/thrift/jmxutils-1.24.jar, file:/data/trino/plugin/thrift/joda-time-2.12.5.jar, file:/data/trino/plugin/thrift/json-235.jar, file:/data/trino/plugin/thrift/jsr305-3.0.2.jar, file:/data/trino/plugin/thrift/log-235.jar, file:/data/trino/plugin/thrift/log-manager-235.jar, file:/data/trino/plugin/thrift/log4j-api-2.17.1.jar, file:/data/trino/plugin/thrift/log4j-over-slf4j-2.0.9.jar, file:/data/trino/plugin/thrift/log4j-to-slf4j-2.17.1.jar, file:/data/trino/plugin/thrift/logback-core-1.4.8.jar, file:/data/trino/plugin/thrift/modernizer-maven-annotations-2.7.0.jar, file:/data/trino/plugin/thrift/netty-all-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-buffer-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-codec-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-codec-dns-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-codec-haproxy-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-codec-http-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-codec-http2-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-codec-memcache-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-codec-mqtt-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-codec-redis-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-codec-smtp-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-codec-socks-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-codec-stomp-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-codec-xml-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-common-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-handler-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-handler-proxy-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-handler-ssl-ocsp-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-resolver-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-resolver-dns-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-resolver-dns-classes-macos-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-resolver-dns-native-macos-4.1.99.Final-osx-aarch_64.jar, file:/data/trino/plugin/thrift/netty-resolver-dns-native-macos-4.1.99.Final-osx-x86_64.jar, file:/data/trino/plugin/thrift/netty-transport-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-transport-classes-epoll-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-transport-classes-kqueue-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-transport-native-epoll-4.1.99.Final-linux-aarch_64.jar, file:/data/trino/plugin/thrift/netty-transport-native-epoll-4.1.99.Final-linux-x86_64.jar, file:/data/trino/plugin/thrift/netty-transport-native-kqueue-4.1.99.Final-osx-aarch_64.jar, file:/data/trino/plugin/thrift/netty-transport-native-kqueue-4.1.99.Final-osx-x86_64.jar, file:/data/trino/plugin/thrift/netty-transport-native-unix-common-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-transport-rxtx-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-transport-sctp-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-transport-udt-4.1.99.Final.jar, file:/data/trino/plugin/thrift/node-235.jar, file:/data/trino/plugin/thrift/opentelemetry-semconv-1.30.1-alpha.jar, file:/data/trino/plugin/thrift/security-235.jar, file:/data/trino/plugin/thrift/slf4j-api-2.0.9.jar, file:/data/trino/plugin/thrift/slf4j-jdk14-2.0.9.jar, file:/data/trino/plugin/thrift/stats-235.jar, file:/data/trino/plugin/thrift/trace-token-235.jar, file:/data/trino/plugin/thrift/trino-cache-428.jar, file:/data/trino/plugin/thrift/trino-matching-428.jar, file:/data/trino/plugin/thrift/trino-plugin-toolkit-428.jar, file:/data/trino/plugin/thrift/trino-thrift-428-services.jar, file:/data/trino/plugin/thrift/trino-thrift-428.jar, file:/data/trino/plugin/thrift/trino-thrift-api-428.jar, file:/data/trino/plugin/thrift/units-1.10.jar]
trino           | java.lang.IllegalStateException: No service providers of type io.trino.spi.Plugin in the classpath: [file:/data/trino/plugin/thrift/HdrHistogram-2.1.9.jar, file:/data/trino/plugin/thrift/aopalliance-1.0.jar, file:/data/trino/plugin/thrift/asm-9.6.jar, file:/data/trino/plugin/thrift/asm-analysis-9.6.jar, file:/data/trino/plugin/thrift/asm-tree-9.6.jar, file:/data/trino/plugin/thrift/asm-util-9.6.jar, file:/data/trino/plugin/thrift/bootstrap-235.jar, file:/data/trino/plugin/thrift/byte-buddy-1.14.8.jar, file:/data/trino/plugin/thrift/bytecode-1.5.jar, file:/data/trino/plugin/thrift/checker-qual-3.37.0.jar, file:/data/trino/plugin/thrift/classmate-1.5.1.jar, file:/data/trino/plugin/thrift/concurrent-235.jar, file:/data/trino/plugin/thrift/configuration-235.jar, file:/data/trino/plugin/thrift/drift-api-1.21.jar, file:/data/trino/plugin/thrift/drift-client-1.21.jar, file:/data/trino/plugin/thrift/drift-codec-1.21.jar, file:/data/trino/plugin/thrift/drift-protocol-1.21.jar, file:/data/trino/plugin/thrift/drift-transport-netty-1.21.jar, file:/data/trino/plugin/thrift/drift-transport-spi-1.21.jar, file:/data/trino/plugin/thrift/error_prone_annotations-2.22.0.jar, file:/data/trino/plugin/thrift/failureaccess-1.0.1.jar, file:/data/trino/plugin/thrift/guava-32.1.2-jre.jar, file:/data/trino/plugin/thrift/guice-7.0.0.jar, file:/data/trino/plugin/thrift/hibernate-validator-8.0.1.Final.jar, file:/data/trino/plugin/thrift/http-client-235.jar, file:/data/trino/plugin/thrift/http2-client-11.0.15.jar, file:/data/trino/plugin/thrift/http2-common-11.0.15.jar, file:/data/trino/plugin/thrift/http2-hpack-11.0.15.jar, file:/data/trino/plugin/thrift/http2-http-client-transport-11.0.15.jar, file:/data/trino/plugin/thrift/j2objc-annotations-2.8.jar, file:/data/trino/plugin/thrift/jackson-core-2.15.2.jar, file:/data/trino/plugin/thrift/jackson-databind-2.15.2.jar, file:/data/trino/plugin/thrift/jackson-datatype-guava-2.15.2.jar, file:/data/trino/plugin/thrift/jackson-datatype-jdk8-2.15.2.jar, file:/data/trino/plugin/thrift/jackson-datatype-joda-2.15.2.jar, file:/data/trino/plugin/thrift/jackson-datatype-jsr310-2.15.2.jar, file:/data/trino/plugin/thrift/jackson-module-parameter-names-2.15.2.jar, file:/data/trino/plugin/thrift/jakarta.annotation-api-2.1.1.jar, file:/data/trino/plugin/thrift/jakarta.inject-api-2.0.1.jar, file:/data/trino/plugin/thrift/jakarta.validation-api-3.0.2.jar, file:/data/trino/plugin/thrift/jboss-logging-3.4.3.Final.jar, file:/data/trino/plugin/thrift/jcl-over-slf4j-2.0.9.jar, file:/data/trino/plugin/thrift/jetty-alpn-client-11.0.15.jar, file:/data/trino/plugin/thrift/jetty-alpn-java-client-11.0.15.jar, file:/data/trino/plugin/thrift/jetty-client-11.0.15.jar, file:/data/trino/plugin/thrift/jetty-http-11.0.15.jar, file:/data/trino/plugin/thrift/jetty-io-11.0.15.jar, file:/data/trino/plugin/thrift/jetty-util-11.0.15.jar, file:/data/trino/plugin/thrift/jmxutils-1.24.jar, file:/data/trino/plugin/thrift/joda-time-2.12.5.jar, file:/data/trino/plugin/thrift/json-235.jar, file:/data/trino/plugin/thrift/jsr305-3.0.2.jar, file:/data/trino/plugin/thrift/log-235.jar, file:/data/trino/plugin/thrift/log-manager-235.jar, file:/data/trino/plugin/thrift/log4j-api-2.17.1.jar, file:/data/trino/plugin/thrift/log4j-over-slf4j-2.0.9.jar, file:/data/trino/plugin/thrift/log4j-to-slf4j-2.17.1.jar, file:/data/trino/plugin/thrift/logback-core-1.4.8.jar, file:/data/trino/plugin/thrift/modernizer-maven-annotations-2.7.0.jar, file:/data/trino/plugin/thrift/netty-all-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-buffer-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-codec-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-codec-dns-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-codec-haproxy-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-codec-http-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-codec-http2-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-codec-memcache-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-codec-mqtt-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-codec-redis-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-codec-smtp-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-codec-socks-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-codec-stomp-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-codec-xml-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-common-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-handler-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-handler-proxy-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-handler-ssl-ocsp-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-resolver-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-resolver-dns-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-resolver-dns-classes-macos-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-resolver-dns-native-macos-4.1.99.Final-osx-aarch_64.jar, file:/data/trino/plugin/thrift/netty-resolver-dns-native-macos-4.1.99.Final-osx-x86_64.jar, file:/data/trino/plugin/thrift/netty-transport-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-transport-classes-epoll-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-transport-classes-kqueue-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-transport-native-epoll-4.1.99.Final-linux-aarch_64.jar, file:/data/trino/plugin/thrift/netty-transport-native-epoll-4.1.99.Final-linux-x86_64.jar, file:/data/trino/plugin/thrift/netty-transport-native-kqueue-4.1.99.Final-osx-aarch_64.jar, file:/data/trino/plugin/thrift/netty-transport-native-kqueue-4.1.99.Final-osx-x86_64.jar, file:/data/trino/plugin/thrift/netty-transport-native-unix-common-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-transport-rxtx-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-transport-sctp-4.1.99.Final.jar, file:/data/trino/plugin/thrift/netty-transport-udt-4.1.99.Final.jar, file:/data/trino/plugin/thrift/node-235.jar, file:/data/trino/plugin/thrift/opentelemetry-semconv-1.30.1-alpha.jar, file:/data/trino/plugin/thrift/security-235.jar, file:/data/trino/plugin/thrift/slf4j-api-2.0.9.jar, file:/data/trino/plugin/thrift/slf4j-jdk14-2.0.9.jar, file:/data/trino/plugin/thrift/stats-235.jar, file:/data/trino/plugin/thrift/trace-token-235.jar, file:/data/trino/plugin/thrift/trino-cache-428.jar, file:/data/trino/plugin/thrift/trino-matching-428.jar, file:/data/trino/plugin/thrift/trino-plugin-toolkit-428.jar, file:/data/trino/plugin/thrift/trino-thrift-428-services.jar, file:/data/trino/plugin/thrift/trino-thrift-428.jar, file:/data/trino/plugin/thrift/trino-thrift-api-428.jar, file:/data/trino/plugin/thrift/units-1.10.jar]
trino           | 	at com.google.common.base.Preconditions.checkState(Preconditions.java:835)
trino           | 	at io.trino.server.PluginManager.loadPlugin(PluginManager.java:167)
trino           | 	at io.trino.server.PluginManager.loadPlugin(PluginManager.java:157)
trino           | 	at io.trino.server.ServerPluginsProvider.lambda$loadPlugins$1(ServerPluginsProvider.java:57)
trino           | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
trino           | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
trino           | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
trino           | 	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
trino           | 	at java.base/java.util.concurrent.ExecutorCompletionService.submit(ExecutorCompletionService.java:184)
trino           | 	at io.trino.util.Executors.executeUntilFailure(Executors.java:41)
trino           | 	at io.trino.server.ServerPluginsProvider.loadPlugins(ServerPluginsProvider.java:52)
trino           | 	at io.trino.server.PluginManager.loadPlugins(PluginManager.java:139)
trino           | 	at io.trino.server.Server.doStart(Server.java:141)
trino           | 	at io.trino.server.Server.lambda$start$0(Server.java:91)
trino           | 	at io.trino.$gen.Trino_428____20240319_195330_1.run(Unknown Source)
trino           | 	at io.trino.server.Server.start(Server.java:91)
trino           | 	at io.trino.server.TrinoServer.main(TrinoServer.java:38)
trino           | 
trino           | 
trino exited with code 100

**Comment by alberttwong** [comment]
Which demo are you using?   How are you starting Trino?

**Comment by hz-git** [comment]
Hi，have you resolved this issue? I have encountered the same PR as you, But I do not know how to resolve this PR.
